web/urls.py
from django.urls import include, path, re_path

from web.views import account
from web.views import project
from web.views import wiki

app_name = 'web'

urlpatterns = [
    # 注册
    path('register/', account.register, name='register'),
    # path('verify/username/', account.verify_username, name='verify_username'),

    # 图片验证码
    path('img/code/', account.img_code, name='img_code'),

    # 手机号登录
    path('login/user_phone/', account.login_phone, name='login_phone'),

    # 用户名登录
    path('login/user_name/', account.login_name, name='login_name'),

    # 邮箱登录
    path('login/user_email/', account.login_email, name='login_email'),

    # 退出登录
    path('logout/', account.logout, name='logout'),

    # 首页
    path('index/', account.index, name='index'),

    # 帮助文档
    path('help/', account.help, name='help'),

    # 创建项目
    path('project/add/', project.project_add, name='project_add'),

    # 展示项目
    path('project/list/', project.project_list, name='project_list'),

    # wiki
    re_path(r'^(?P<user_id>\d+)/wiki/$', wiki.wiki, name='wiki'),

    # 新建文章
    re_path(r'^(?P<user_id>\d+)/wiki/add/$', wiki.wiki_add, name='wiki_add'),

    # 展示多级目录
    re_path(r'^(?P<user_id>\d+)/wiki/catalog/$', wiki.wiki_catalog, name='wiki_catalog'),

    # 删除文章
    re_path(r'^(?P<user_id>\d+)/wiki/delete/(?P<wiki_id>\d+)/$', wiki.wiki_delete, name='wiki_delete'),

    # 编辑文章
    re_path(r'^(?P<user_id>\d+)/wiki/edit/(?P<wiki_id>\d+)/$', wiki.wiki_edit, name='wiki_edit'),

    # 上传图片
    re_path(r'^(?P<user_id>\d+)/wiki/upload/$', wiki.wiki_upload, name='wiki_upload'),

    # 星标项目
    re_path(r'^project/star/(?P<project_type>\w+)/(?P<project_id>\d+)/$', project.project_star, name='project_star'),

    # 取消星标
    re_path(r'^project/delete_star/(?P<project_type>\w+)/(?P<project_id>\d+)/$', project.project_delete_star,
            name='project_delete_star'),

    # 图像分割
    re_path(r'^project/image_segmentation/(?P<project_id>\d+)/$', project.project_image_segmentation,
            name='project_image_segmentation'),

    # 进行图像分割
    re_path(r'^project/image_segmentation/(?P<project_id>\d+)/handle/$', project.project_handle,
            name='project_handle'),

    # 下载文件
    re_path(r'^project/image_segmentation/(?P<project_id>\d+)/file_download/(?P<original_img_id>\d+)/$', project.file_download,
            name='file_download'),

    # 项目管理
    re_path(r'^project/manage/(?P<project_id>\d+)/$', project.project_manage, name='project_manage'),

    # 获取临时凭证
    path('project/cos/credential/', project.cos_credential, name='cos_credential'),

    # 把文件写入数据库
    re_path(r'^project/manage/(?P<project_id>\d+)/post/$', project.project_file_post, name='project_file_post'),

]

web/models.py
from collections import deque

from django.db import models


class UserInfo(models.Model):
    user_name = models.CharField(verbose_name='用户名', max_length=32, db_index=True)  # db_index=True创建索引

    user_email = models.EmailField(verbose_name='邮箱', max_length=32)  # 内置正则表达式

    user_phone = models.CharField(verbose_name='手机号', max_length=32)

    user_pw = models.CharField(verbose_name='密码', max_length=32)

    bucket = models.CharField(verbose_name='cos桶', max_length=128)

    region = models.CharField(verbose_name='cos区域', max_length=32)


class Project(models.Model):
    COLOR_CHOICES = (
        (1, "#56b8eb"),
        (2, "#f28033"),
        (3, "#ebc656"),
        (4, "#a2d148"),
        (5, "#20bfa4"),
        (6, "#7461c2"),
        (7, "#20bfa3"),
    )

    name = models.CharField(verbose_name='项目名称', max_length=32)

    description = models.TextField(verbose_name='项目描述', max_length=300)

    color = models.SmallIntegerField(verbose_name='项目颜色', choices=COLOR_CHOICES, default=1)

    star = models.BooleanField(verbose_name='项目星标', default=False)

    project_time = models.DateTimeField(verbose_name='创建时间', auto_now_add=True)

    user = models.ForeignKey(UserInfo, on_delete=models.CASCADE)  # 外键


class OriginalImage(models.Model):

    original_img_name = models.CharField(verbose_name='本地上传图像名称', max_length=255)

    original_img_key = models.CharField(verbose_name='COS图片名称', max_length=255)

    original_img_path = models.CharField(verbose_name='本地上传图像路径', max_length=255)

    original_img_time = models.DateTimeField(verbose_name='上传时间', auto_now_add=True)

    project = models.ForeignKey(Project, on_delete=models.CASCADE)  # 外键


class SegmentationResult(models.Model):
    MODEL_CHOICES = (
        (1, "unet"),
        (2, "unet_c"),
        (3, "unet_s"),
        (4, "unet_cs"),
        (5, "unet++"),
        (6, "u2net"),
    )

    model_type = models.SmallIntegerField(verbose_name='分割模型', choices=MODEL_CHOICES)

    result_img = models.CharField(verbose_name='分割结果图像', max_length=255)

    result_img_time = models.DateTimeField(verbose_name='分割完成时间', auto_now_add=True)

    original_img = models.ForeignKey(OriginalImage, on_delete=models.CASCADE)  # 外键


class Wiki(models.Model):
    page_title = models.CharField(verbose_name='文章标题', max_length=255)

    page_content = models.TextField(verbose_name='文章内容')

    # auto_now_add=True：当Wiki实例第一次创建时，page_time字段会自动设置为当前时间
    page_time = models.DateTimeField(verbose_name='创建时间', auto_now_add=True)  # 仅在创建时设置

    # auto_now=True：每次保存模型实例时都会更新为当前时间
    update_time = models.DateTimeField(verbose_name='更新时间', auto_now=True)  # 每次修改时更新

    user = models.ForeignKey(UserInfo, on_delete=models.CASCADE)  # 外键

    # 自关联
    # null=True, blank=True：这些参数允许parent字段为空
    parent = models.ForeignKey('Wiki', on_delete=models.CASCADE, null=True, blank=True, related_name='children',
                               verbose_name='父文章')

    # 深度
    depth = models.IntegerField(verbose_name='深度', default=1)

    def __str__(self):
        return self.page_title

    # 父节点depth修改后，修改所有子节点的depth
    def update_children_depth(self):
        queue = deque([self])
        while queue:
            current_node = queue.popleft()
            children = current_node.children.all()
            for child in children:
                child.depth = current_node.depth + 1
                child.save(update_fields=['depth'])
                queue.append(child)

web/forms/wiki.py
from django import forms
from django.core.exceptions import ValidationError
from django.core.validators import RegexValidator

from web import models
from web.forms.bootstrap import BootstrapForm


class WikiAddModelForm(BootstrapForm, forms.ModelForm):
    page_title = forms.CharField(
        label='文章标题',
        min_length=2,
        max_length=255,
        validators=[
            RegexValidator(
                regex=r'^.{2,32}$',  # 正则表达式
                message='文章标题长度为2-255位。'
            )
        ]
    )

    class Meta:
        model = models.Wiki
        fields = ['page_title', 'page_content', 'parent']

    def __init__(self, request, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.request = request  # 把试图里面的对象传到Form中

        total_data_list = [("", "请选择")]
        data_list = models.Wiki.objects.filter(user=request.tracer).values_list('id', 'page_title')
        total_data_list.extend(data_list)

        self.fields['parent'].choices = total_data_list

    def clean_page_title(self):
        page_title = self.cleaned_data['page_title']

        exits = models.Wiki.objects.filter(page_title=page_title,user=self.request.tracer).exists()

        if exits:
            raise ValidationError("文章标题已存在。")

        return page_title


class WikiEditModelForm(BootstrapForm, forms.ModelForm):
    page_title = forms.CharField(
        label='文章标题',
        min_length=2,
        max_length=255,
        validators=[
            RegexValidator(
                regex=r'^.{2,32}$',  # 正则表达式
                message='文章标题长度为2-255位。'
            )
        ]
    )

    class Meta:
        model = models.Wiki
        fields = ['page_title', 'page_content', 'parent']

    def __init__(self, request, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.request = request  # 把试图里面的对象传到Form中

        total_data_list = [("", "请选择")]
        data_list = models.Wiki.objects.filter(user=request.tracer).values_list('id', 'page_title')
        total_data_list.extend(data_list)

        self.fields['parent'].choices = total_data_list

    def clean_page_title(self):
        page_title = self.cleaned_data['page_title']

        # 获取当前用户的所有同标题文章
        queryset = models.Wiki.objects.filter(
            page_title=page_title,
            user=self.request.tracer
        )

        # 编辑时排除自己（新建时instance.id不存在）
        if self.instance.pk:
            queryset = queryset.exclude(id=self.instance.pk)

        if queryset.exists():
            raise ValidationError("文章标题已存在。")

        return page_title

web/views/wiki.py
from django.http import JsonResponse
from django.shortcuts import render, HttpResponse, redirect
from web import models
from django.urls import reverse

from web.forms.wiki import WikiAddModelForm
from web.forms.wiki import WikiEditModelForm

from django.views.decorators.csrf import csrf_exempt
from utils.encrypt import uid
from utils.tencent.cos import upload_file


def wiki(request, user_id):
    """wiki首页"""
    wiki_id = request.GET.get('wiki_id')

    # 如果传入的wiki_id不是数字
    if not wiki_id or not wiki_id.isdecimal():
        return render(request, "web/wiki.html")

    wiki_object = models.Wiki.objects.filter(id=wiki_id, user_id=request.tracer).first()

    print("wiki_object:", wiki_object)
    print("wiki_object.page_content:", wiki_object.page_content)

    return render(request, "web/wiki.html", {"wiki_object": wiki_object})


def wiki_add(request, user_id):
    """添加文章"""

    # 展示添加文章页面
    if request.method == "GET":
        form = WikiAddModelForm(request)
        return render(request, "web/wiki_add.html", {'form': form})

    # 文章校验
    form = WikiAddModelForm(request, data=request.POST)
    if form.is_valid():

        # 判断用户是否选择父文章,设置depth
        if form.instance.parent:
            form.instance.depth = form.instance.parent.depth + 1
        else:
            form.instance.depth = 1

        form.instance.user = request.tracer
        form.save()
        url = reverse('web:wiki', kwargs={'user_id': user_id})  # 跳转回wiki页面
        print("form is_valid")
        print("page", form.cleaned_data)
        print("url", url)
        return JsonResponse({"status": True, "data": url})
    else:
        print("form not_valid")
        print(form.errors)
        return JsonResponse({"status": False, 'error': form.errors})


def wiki_catalog(request, user_id):
    """wiki目录"""

    # 获取当前用户的所有wiki文章
    # data = models.Wiki.objects.filter(user=request.tracer).values("id", "page_title", "parent_id")
    data = models.Wiki.objects.filter(user=request.tracer).values("id", "page_title", "parent_id").order_by("depth",
                                                                                                            "id")
    # 将QuerySet转换为列表
    data_list = list(data)

    print("data_list:", data_list)

    return JsonResponse({"status": True, "data": data_list})


def wiki_delete(request, user_id, wiki_id):
    models.Wiki.objects.filter(id=wiki_id, user_id=user_id).delete()
    url = reverse('web:wiki', kwargs={'user_id': user_id})  # 跳转回wiki页面
    return redirect(url)


def wiki_edit(request, user_id, wiki_id):
    # 获取wiki对象
    wiki_object = models.Wiki.objects.filter(id=wiki_id, user_id=user_id).first()

    # wiki对象不存在
    if not wiki_object:
        url = reverse('web:wiki', kwargs={'user_id': user_id})  # 跳转回wiki页面
        return redirect(url)

    # 显示文章原始内容
    if request.method == "GET":
        form = WikiEditModelForm(request, instance=wiki_object)
        return render(request, "web/wiki_edit.html", {'form': form, 'wiki_object': wiki_object})

    # 提交修改
    if request.method == "POST":
        form = WikiEditModelForm(request, data=request.POST, instance=wiki_object)

        if form.is_valid():

            # 判断用户是否选择父文章,设置depth
            if form.instance.parent:
                form.instance.depth = form.instance.parent.depth + 1
            else:
                form.instance.depth = 1

            form.save()

            # 递归更新子节点的depth
            form.instance.update_children_depth()

            url = reverse('web:wiki', kwargs={'user_id': user_id})  # 跳转回wiki页面

            preview_url = "{0}?preview={1}".format(url, form.instance.id)  # 跳转到编辑后的文章页面

            return JsonResponse({"status": True, "data": preview_url})
        else:
            print("form not_valid")
            print(form.errors)
            return JsonResponse({"status": False, 'error': form.errors})


# 去掉csrf认证
@csrf_exempt
def wiki_upload(request, user_id):
    """markdown插件上传图片"""
    print("收到图片",request.FILES)

    # 图片对象
    image_object = request.FILES.get("editormd-image-file")

    if not image_object:
        # 将结果返回给markdown组件【失败】
        result = {
            "success": 0,
            "message": "文件不存在。",
        }
        return JsonResponse(result)

    # 检查文件扩展名
    filename = image_object.name        # 上传的文件名

    parts = filename.rsplit('.', 1)

    if len(parts) < 2:
        result = {
            "success": 0,
            "message": "文件缺少扩展名。",
            "url": None
        }
        return JsonResponse(result)

    ext = parts[1].lower()      # 文件后缀名

    # 随机文件名
    key = "{}.{}".format(uid(request.tracer.user_phone), ext)

    # 上传到COS
    try:
        image_url = upload_file(
            request.tracer.bucket,
            request.tracer.region,
            image_object,
            key
        )
    except Exception as e:
        # 可以记录日志，例如print或者使用logging模块
        print(f"上传到COS失败: {e}")
        result = {
            "success": 0,
            "message": "文件上传失败，请稍后再试。",
            "url": None
        }
        return JsonResponse(result)

    # 检查是否返回了有效的URL（假设上传成功返回非空URL）
    if not image_url:
        result = {
            "success": 0,
            "message": "文件上传失败，无法获取URL。",
            "url": None
        }
        return JsonResponse(result)

    # 成功返回
    result = {
        "success": 1,
        "message": None,
        "url": image_url,
    }
    return JsonResponse(result)

web/templates/web/help.html
{% extends 'web/layout/basic.html' %}
{% load static %}

{% block title %}帮助文档{% endblock %}

{% block css %}

{% endblock %}

{% block content %}

{% endblock %}

{% block js %}

{% endblock %}

web/templates/web/index.html
{% extends 'web/layout/basic.html' %}
{% load static %}

{% block title %}首页{% endblock %}

{% block css %}
    <link rel="stylesheet" href="{% static 'web/css/account.css' %}">
    <style>
        .bk_img img {
            width: auto;  /* 设置宽度为 100%，根据父元素的宽度调整 */
            max-width: 100%; /* 确保图片不会超出父元素的宽度 */
            height: auto;  /* 高度自动调整，保持比例 */
        }
    </style>
{% endblock %}

{% block content %}
    <div class="bk_img">
        <img src="{% static 'web/img/bg_img.jpg' %}" alt="Background Image">
    </div>
    
    <footer class="footer">
        <p class="tex1">202125310617计算机6班苏埼丹</p>
        <p class="tex2">时间：2025年2月</p>
    </footer>
{% endblock %}



{% block js %}

{% endblock %}

web/templates/web/project_list.html
{% extends 'web/layout/basic.html' %}
{% load static %}

{% block title %}项目列表{% endblock %}

{% block css %}
    <link rel="stylesheet" href="{% static 'web/css/project.css' %}">
{% endblock %}

{% block content %}
    <div class="project container-fluid">

        <div class="card">
            <div class="card-header">
                <i class="fa-solid fa-star"></i>
                星标项目
            </div>
            <div class="card-body">
                {% for item in project_dict.star %}
                    <div class="item">
                        <a href="/web/project/manage/{{ item.id }}/" class="title"
                           style="background-color: {{ item.get_color_display }};">{{ item.name }}</a>
                        <div class="info">
                            <div>
                                <a href="/web/project/delete_star/my/{{ item.id }}/">
                                    <i class="fa-solid fa-star" aria-hidden="true" style="color: #FCD53F"></i>
                                </a>
                                <span>{{ item.project_time }}</span>
                            </div>

                        </div>
                    </div>

                {% endfor %}
            </div>
        </div>

        <div class="card">
            <div class="card-header">
                <i class="fa-solid fa-list"></i>
                我创建的项目
            </div>
            <div id="projectItem" class="card-body">
                {% for item in project_dict.my %}
                    <div class="item">
                        <a href="/web/project/manage/{{ item.id }}/" class="title"
                           style="background-color: {{ item.get_color_display }};">{{ item.name }}</a>
                        <div class="info">
                            <div>
                                <a href="/web/project/star/my/{{ item.id }}/">
                                    <i class="fa-solid fa-star" aria-hidden="true" style="color: #d5d5d5"></i>
                                </a>
                                <span>{{ item.project_time }}</span>
                            </div>

                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>

    </div>

{% endblock %}



{% block js %}


{% endblock %}

web/templates/web/register.html
{% extends 'web/layout/basic.html' %}
{% load static %}

{% block title %}用户注册{% endblock %}

{% block css %}
    <link rel="stylesheet" href="{% static 'web/css/account.css' %}">
{% endblock %}

{% block content %}
    <div class="account">
        <div class="title">用户注册</div>

        <form id="regForm" method="post" novalidate>
            {% csrf_token %}

            {% for field in form %}
                <div class="form-group mb-3">
                    <label for="{{ field.id_for_label }}" class="form-label">{{ field.label }}</label>
                    {{ field }}
                    <span class="error-msg"></span>
                </div>
            {% endfor %}
            <div class="text-center">
                <button id="submitBtn" type="button" class="btn btn-primary">提交</button>
            </div>
        </form>

    </div>

{% endblock %}

{% block js %}
    <script>
        // 页面框架加载完成之后自动执行函数
        $(function () {
            bindClickSubmitBtn();
        });

        /*
        点击提交按钮绑定事件
         */
        function bindClickSubmitBtn() {
            console.log('绑定事件')

            $('#submitBtn').click(function () {
                console.log('按钮被点击')

                $('.error-msg').empty();

                console.log('清空原信息')

                $.ajax({
                    url: "/web/register/",
                    type: "POST",
                    data: $('#regForm').serialize(),     // 收集表单数据,所有字段+csrf
                    dataType: "JSON",
                    success: function (res) {
                        if (res.status) {
                            location.href = res.data;
                        } else {
                            console.log('错误字段')
                            $.each(res.error, function (key, value) {
                                $("#id_" + key).next().text(value[0]);

                            })
                        }
                    }
                })
                console.log('发送ajax请求')

            })

            {% comment %}console.log('绑定事件');

            $('#submitBtn').click(function () {
                // event.preventDefault();  // 阻止默认的表单提交行为

                console.log('按钮被点击');

                $('.error-msg').empty();

                // 获取用户名
                var userName = $('#id_user_name').val();

                var baseUrl = window.location.origin;

                // 发送ajax请求
                $.ajax({
                    // 最前面加斜杠表示从根路径开始
                    // 必须这样写，否则url是http://localhost:8000/web/register/verify/username/
                    url: "/web/verify/username/",
                    type: "GET",
                    data: {user_name: userName, tpl: 'register'},  //发送数据
                    dataType:"JSON",    //将后端返回的数据反序列化为字典
                    success: function (res) {
                        // ajax请求发送成功后，自动执行的函数；res就是后端返回的值
                        if(res.status === 'true'){
                            // 继续检验第二个字段

                        }else {
                            $.each(res.error,function (key,value) {
                                console.log(key)
                                $("#id_"+key).next().text(value[0]);

                            })
                        }
                    }
                })

                // 获取邮箱
                var userEmail = $('id_user_email').val();

                // 获取手机号
                var userPhone = $('id_user_phone').val();
            }){% endcomment %}


        }
    </script>
{% endblock %}

web/templates/web/wiki_add.html
{% extends 'web/layout/basic.html' %}
{% load static %}

{% block title %}wiki{% endblock %}

{% block css %}
    <link rel="stylesheet" href="{% static 'web/css/wiki.css' %}">
    <link rel="stylesheet" href="{% static 'web/plugin/editor-md/css/editormd.min.css' %}">

{% endblock %}


{% block content %}
    <div class="container-fluid">
        <div class="card">

            <div class="card-header">
                <div class="head">
                    <i class="fa-solid fa-square-plus"></i>
                    新建文章
                </div>
            </div>

            <div class="card-body">
                <div class="col-sm-3 title-list">
                    <ul id="catalog">

                    </ul>
                </div>

                <div class="col-sm-6 content">

                    <form id="addPageForm" method="post">
                        {% csrf_token %}
                        {% for field in form %}
                            {% if field.name == "page_content" %}
                                <div class="form-group mb-3">
                                    <label for="{{ field.id_for_label }}" class="form-label">{{ field.label }}</label>
                                    <div id="editor">
                                        {{ field }}
                                    </div>
                                    <span class="error-msg"></span>
                                </div>
                            {% else %}
                                <div class="form-group mb-3">
                                    <label for="{{ field.id_for_label }}" class="form-label">{{ field.label }}</label>
                                    {{ field }}
                                    <span class="error-msg"></span>
                                </div>
                            {% endif %}
                        {% endfor %}
                        <div class="text-center">
                            <button id="submitBtn" type="button" class="btn btn-primary">提交</button>
                        </div>
                    </form>

                </div>
            </div>

        </div>
    </div>
{% endblock %}

{% block js %}
    <script src="{% static "web/plugin/editor-md/editormd.min.js" %}"></script>
    <script>
        var WIKI_DETAIL_URL = "{% url 'web:wiki' user_id=request.tracer.id %}";     //全局变量
        var WIKI_UPLOAD_URL = "{% url 'web:wiki_upload' user_id=request.tracer.id %}"

        $(function () {
            initCatalog();      //初始化多级目录
            bindClickSubmitBtn();
            initEditorMd();
        });

        /*
        初始化markdown编辑器：textare转换为编辑器
        插件会从本地接收图片，并发送给后端
         */
        function initEditorMd() {
            editormd('editor',{
                placeholder:"请输入内容",
                height:500,
                path:"{% static "web/plugin/editor-md/lib/" %}",
                imageUpload:true,
                imageFormats:["jpg","jpeg","png","gif"],
                imageUploadURL:WIKI_UPLOAD_URL
            })
        }

        function initCatalog() {
            $.ajax({
                url: "{% url 'web:wiki_catalog' user_id=request.tracer.id %}",
                type: "GET",
                dataType: "JSON",
                success: function (res) {
                    console.log(res);
                    if (res.status) {
                        $.each(res.data, function (index, item) {
                            //item={'id': 1, 'page_title': '病人01', 'parent_id': None}
                            var href = WIKI_DETAIL_URL + "?wiki_id=" + item.id;     //文章访问路径

                            var li = $("<li>").attr("id", "id_" + item.id).append($("<a>").text(item.page_title).attr("href", href)).append($("<ul>"));

                            if (!item.parent_id) {

                                $("#catalog").append(li);

                            } else {

                                $("#id_" + item.parent_id).children("ul").append(li);
                            }
                        })
                    } else {
                        alert("初始化目录失败。")
                    }
                }
            })
        }

        /*
        点击提交按钮绑定事件
         */
        function bindClickSubmitBtn() {
            console.log('绑定事件')

            $('#submitBtn').click(function () {
                console.log('按钮被点击')

                $('.error-msg').empty();

                console.log('清空原信息')

                $.ajax({
                    url: "{% url 'web:wiki_add' user_id=request.tracer.id %}",
                    type: "POST",
                    data: $('#addPageForm').serialize(),     // 收集表单数据,所有字段+csrf
                    dataType: "JSON",
                    success: function (res) {
                        if (res.status) {
                            location.href = res.data;
                        } else {
                            console.log('错误字段')
                            $.each(res.error, function (key, value) {
                                $("#id_" + key).next().text(value[0]);
                            })
                        }
                    }
                })
                console.log('发送ajax请求')

            })

        }
    </script>
{% endblock %}

web/templates/web/wiki_edit.html
{% extends 'web/layout/basic.html' %}
{% load static %}

{% block title %}wiki{% endblock %}

{% block css %}
    <link rel="stylesheet" href="{% static 'web/css/wiki.css' %}">
    <link rel="stylesheet" href="{% static 'web/plugin/editor-md/css/editormd.min.css' %}">
{% endblock %}


{% block content %}
    <div class="container-fluid">
        <div class="card">

            <div class="card-header">
                <div class="head">
                    <i class="fa-solid fa-pen-to-square"></i>
                    编辑文章
                </div>
            </div>

            <div class="card-body">
                <div class="col-sm-3 title-list">
                    <ul id="catalog">

                    </ul>
                </div>

                <div class="col-sm-6 content">

                    <form id="editPageForm" method="post">
                        {% csrf_token %}
                        {% for field in form %}
                            {% if field.name == "page_content" %}
                                <div class="form-group mb-3">
                                    <label for="{{ field.id_for_label }}" class="form-label">{{ field.label }}</label>
                                    <div id="editor">
                                        {{ field }}
                                    </div>
                                    <span class="error-msg"></span>
                                </div>
                            {% else %}
                                <div class="form-group mb-3">
                                    <label for="{{ field.id_for_label }}" class="form-label">{{ field.label }}</label>
                                    {{ field }}
                                    <span class="error-msg"></span>
                                </div>
                            {% endif %}
                        {% endfor %}
                        <div class="text-center">
                            <button id="submitBtn" type="button" class="btn btn-primary">提交</button>
                        </div>
                    </form>

                </div>
            </div>

        </div>
    </div>
{% endblock %}

{% block js %}
    <script src="{% static "web/plugin/editor-md/editormd.min.js" %}"></script>

    <script>
        var WIKI_DETAIL_URL = "{% url 'web:wiki' user_id=request.tracer.id %}";     //全局变量
        var WIKI_UPLOAD_URL = "{% url 'web:wiki_upload' user_id=request.tracer.id %}"

        $(function () {
            initCatalog();      //初始化多级目录
            bindClickSubmitBtn();
            initEditorMd();
        });

        /*
        初始化markdown编辑器：textare转换为编辑器
         */
        function initEditorMd() {
            editormd('editor',{
                placeholder:"请输入内容",
                height:500,
                path:"{% static "web/plugin/editor-md/lib/" %}",
                imageUpload:true,
                imageFormats:["jpg","jpeg","png","gif"],
                imageUploadURL:WIKI_UPLOAD_URL
            })
        }

        function initCatalog() {
            $.ajax({
                url: "{% url 'web:wiki_catalog' user_id=request.tracer.id%}",
                type: "GET",
                dataType: "JSON",
                success: function (res) {
                    console.log(res);
                    if (res.status) {
                        $.each(res.data, function (index, item) {
                            //item={'id': 1, 'page_title': '病人01', 'parent_id': None}
                            var href = WIKI_DETAIL_URL + "?wiki_id=" + item.id;     //文章访问路径

                            var li = $("<li>").attr("id", "id_" + item.id).append($("<a>").text(item.page_title).attr("href", href)).append($("<ul>"));

                            if (!item.parent_id) {

                                $("#catalog").append(li);

                            } else {

                                $("#id_" + item.parent_id).children("ul").append(li);
                            }
                        })
                    } else {
                        alert("初始化目录失败。")
                    }
                }
            })
        }

        /*
        点击提交按钮绑定事件
         */
        function bindClickSubmitBtn() {
            console.log('绑定事件')

            $('#submitBtn').click(function () {
                console.log('按钮被点击')

                $('.error-msg').empty();

                console.log('清空原信息')

                $.ajax({
                    url: "{% url 'web:wiki_edit' user_id=request.tracer.id wiki_id=wiki_object.id %}",
                    type: "POST",
                    data: $('#editPageForm').serialize(),     // 收集表单数据,所有字段+csrf
                    dataType: "JSON",
                    success: function (res) {
                        if (res.status) {
                            location.href = res.data;
                        } else {
                            console.log('错误字段')
                            $.each(res.error, function (key, value) {
                                $("#id_" + key).next().text(value[0]);
                            })
                        }
                    }
                })
                console.log('发送ajax请求')

            })

        }
    </script>
{% endblock %}